{
 "title": "Chia",
 "description": "Chia Network",
 "tags": [
  "system",
  "prometheus",
  "online",
  "home"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": { "query": "label_values($tag)" } },
   { "name": "tag", "query": "instance, alias" }
  ]
 },
 "panels": [
  { "title": "Farming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_blockchain_sync_status", "legendFormat": " " }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_peers_count{type=\"1\"}"
    }
   ]
  },
  {
   "title": "Mojo",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "chia_wallet_confirmed_balance_mojo",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "Relative Plot Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "chia_farm_summary_total_plot_size /chia_farm_summary_estimated_network_space * 100"
    }
   ]
  },
  {
   "title": "Time To Win",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farm_summary_expected_time_to_win",
     "legendFormat": "ETW"
    }
   ]
  },
  {
   "title": "Plot Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_harvester_plots_total{instance=\"qnap:3903\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "XCH-USD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coin_market_quote_USD" }
   ]
  },
  {
   "title": "Challenge Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chia_harvester_blocks_total{instance=\"qnap:3903\"}[5m])",
     "legendFormat": "Blocks"
    },
    {
     "expr": "rate(chia_harvester_plots_eligible{instance=\"qnap:3903\"}[5m])/chia_harvester_plots_total{instance=\"qnap:3903\"}",
     "legendFormat": "Eligible Plots"
    }
   ]
  },
  {
   "title": "Search Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chia_harvester_search_time_bucket{le=\"+Inf\", plots_eligible!=\"0\"}[5m])"
    },
    {
     "expr": "rate(chia_harvester_search_time_bucket{le=\"30\", plots_eligible!=\"0\"}[5m])"
    },
    {
     "expr": "rate(chia_harvester_search_time_bucket{le=\"10\", plots_eligible!=\"0\"}[5m])"
    }
   ]
  },
  {
   "title": "Search Time Buckets",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_search_time_bucket{instance=\"qnap:3903\",plots_eligible!=\"0\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cpuUsage{job='snmp_qnap'})/4",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "systemTotalMemEX{job='snmp_qnap'}-rate(systemFreeMemEX{job='snmp_qnap'}[5m])",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Plotting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plotman_jobs_count_phase_1+plotman_jobs_count_phase_2+plotman_jobs_count_phase_3+plotman_jobs_count_phase_4",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_harvester_plots_total{instance=\"qnap:3903\"}[1d])*60*60*24",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Farm Disk Space",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(node_filesystem_avail_bytes{mountpoint=~\"/mnt/farmers/.+\"},\"mountpoint\", \"$1\", \"mountpoint\", \"/mnt/farmers/(.*)\")",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_disk_written_bytes_total{device=~\"nvme[0-2]n1\"}[5m])",
     "legendFormat": "{{device}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(node_filesystem_size_bytes{mountpoint=~\"/mnt/plotter[1-3]+\"}-node_filesystem_avail_bytes{mountpoint=~\"/mnt/plotter[1-3]+\"})/1000",
     "legendFormat": "{{mountpoint}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=~\"/mnt/farmers/.+\"})/(108877420954*(sum(rate(chia_harvester_plots_total{instance=\"qnap:3903\"}[1d]))))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-sum(node_filesystem_avail_bytes{mountpoint=~\"/mnt/farmers/farmer[0-9]\"})/sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/farmers/farmer[0-9]\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Current Phases",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plotman_jobs_count_phase_1", "legendFormat": "1" },
    { "expr": "plotman_jobs_count_phase_2", "legendFormat": "2" },
    { "expr": "plotman_jobs_count_phase_3", "legendFormat": "3" },
    { "expr": "plotman_jobs_count_phase_4", "legendFormat": "4" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(irate(node_cpu_seconds_total{$tag=\"$host\",mode=\"nice\"}[5m]))  * 100 / count(node_cpu_seconds_total{$tag=\"$host\",mode=\"nice\"}) ",
     "legendFormat": "Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%20by%20(mode)%20*%20100%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes- (node_memory_MemAvailable_bytes or (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes))",
     "legendFormat": "Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{$tag=\"$host\", device=\"enp7s0\"}[$interval]) or irate(node_network_transmit_bytes_total{$tag=\"$host\", device=\"enp7s0\"}[5m])",
     "legendFormat": "Outbound: {{ device }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}