global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'chia_farm_exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['farmer:8000']
  - job_name: 'chia_exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9133']
  - job_name: 'plotman_exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['plotter:8001']
  - job_name: 'coinmarketcap_exporter'
    scrape_interval: 15m
    static_configs:
      - targets: ['localhost:9101']
  - job_name: 'mtail'
    static_configs:
      - targets: ['farmer:3903']
  - job_name: 'snmp_qnap'
    scrape_interval: 1m
    static_configs:
    - targets:
        - 192.168.4.171
    metrics_path: /snmp
    params:
      module: [qnap]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.4.171:9116
